what you like, what you dislike
what are the limits of initiatives I can take?
daily checklists you have for me?
direct supervisor, 
who to report my absence to, 
which line or phone number can I call as an employee?
how does the on-call office hours work? how often?
what does the overtime work?
How late I can stay in office?

Could I get access to your
- SQL Tuning Journal(knowledge base for known issues and how you solve it THEN have alls DBA team's member post any issue they run into and how they solve it.
	it is about learn from others and, more important, save time to the company an new DBA and recreate the wheel
- Monitoring tools 
I need to know  
- your SLA on RPO, RTO, MTTI
- your disaster recovery strategy document: step by step
- the performance's Values(log) on normal conditions of use for CPU, Memory, Network, Disk on the server, I will be working on? 
-if error handling(xabort, tran, @@tran, try/catch) is a norm for insert,update, delete?
-FK and Primary is it a norm?

FOR Monktar, MAKE SURE YOU ALWAYS GET ASSIGNED SMART GOAL
