--For replay
--S:\MSSQL\SQLOS-x86\140\Tools\DReplayController
--S:\MSSQL\SQLOS-x86\140\Tools\DReplayClient\Log
--install from sql installer Replay Controller then REplay client on each machien supposed to run the worload
--run Dcomcnfg services component and grant permissions to the domain account(DCOM Config > DREplay COntroller)
--start the services SQL Replay Controler, SQL Replay CLient
--run Lusrmgr.msc -- User & Group > Distributed Com Users
--netsh advfirewall firewall add rule name="allow dreplay controller" dir=in program="S:\MSSQL\SQLOS-x86\140\Tools\DReplayController\DReplayController.exe" action=allow
--netsh advfirewall firewall add rule name="allow dreplay client" dir=in program="S:\MSSQL\SQLOS-x86\140\Tools\DReplayClient\DReplayClient.exe" action=allow
